version: 2

jobs:
  build-and-test:
    macos:
      xcode: "9.3.0"

    steps:
      - checkout
      - run:
          name: Setup
          command: bin/setup
      - run:
          name: Build and Test
          command: bin/test -r

workflows:
  version: 2
  default:
    jobs:
      - build-and-test
